<?php

namespace Database\Seeders;

use App\Models\Experience;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;

class ExperienceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendor1 = User::where('email', 'vendor1@funtasting.it')->first();
        $vendor2 = User::where('email', 'vendor2@funtasting.it')->first();

        $cultura = Category::where('slug', 'arte-e-cultura')->first();
        $sport = Category::where('slug', 'sport-e-avventura')->first();
        $natura = Category::where('slug', 'natura')->first();
        $enogastronomia = Category::where('slug', 'enogastronomia')->first();

        // Esperienza 1: Tour dei Borghi
        Experience::create([
            'vendor_id' => $vendor1->id,
            'category_id' => $cultura->id,
            'title' => 'Tour dei Borghi Antichi delle Marche',
            'short_description' => 'Scopri i borghi più belli delle Marche con una guida esperta',
            'full_description' => 'Un tour completo alla scoperta dei borghi più affascinanti delle Marche. Visiteremo Gradara, Corinaldo, Offagna e altri gioielli medievali. La guida ti accompagnerà attraverso secoli di storia, arte e tradizioni locali.',
            'languages' => ['it', 'en', 'fr'],
            'has_lis' => false,
            'has_braille' => false,
            'start_time_period' => 'morning',
            'duration' => '5h_to_1day',
            'location_type' => 'borgo',
            'province' => 'ancona',
            'meeting_point' => 'Piazza del Plebiscito, Ancona',
            'latitude' => 43.6158,
            'longitude' => 13.5189,
            'parking_info' => 'Parcheggio disponibile vicino al punto di ritrovo',
            'what_to_bring' => 'Scarpe comode, macchina fotografica, acqua',
            'user_types' => ['singolo', 'coppia', 'amici', 'famiglia', 'senior'],
            'age_groups' => ['6-10', '10-14', '14-18'],
            'group_types' => ['gruppi_15+'],
            'disabilities' => [],
            'pets_allowed' => false,
            'has_offer' => false,
            'free_cancellation' => true,
            'is_new' => true,
            'few_spots_left' => false,
            'tour_type' => 'group',
            'sustainability_score' => 85,
            'small_association' => false,
            'price_adult' => 45.00,
            'price_child' => 25.00,
            'price_senior' => 40.00,
            'price_group' => 40.00,
            'season' => 'high',
            'available_from' => now(),
            'available_to' => now()->addMonths(6),
            'min_participants' => 4,
            'max_participants' => 20,
            'cutoff_hours' => 24,
            'cancellation_policy' => 'flexible',
            'weather_cancellation' => false,
            'indoor_alternative' => false,
            'images' => [],
            'video_url' => null,
            'status' => 'active',
            'rating' => 4.7,
            'reviews_count' => 12,
        ]);

        // Esperienza 2: Canyoning
        Experience::create([
            'vendor_id' => $vendor2->id,
            'category_id' => $sport->id,
            'title' => 'Canyoning nel Gola del Furlo',
            'short_description' => 'Avventura adrenalinica nel canyon naturale del Furlo',
            'full_description' => 'Un\'esperienza indimenticabile di canyoning nella spettacolare Gola del Furlo. Scivolerai tra le acque cristalline, ti tufferai in piscine naturali e ammirerai la natura incontaminata. Attrezzatura professionale inclusa.',
            'languages' => ['it', 'en'],
            'has_lis' => false,
            'has_braille' => false,
            'start_time_period' => 'morning',
            'duration' => '3-5h',
            'location_type' => 'montagna',
            'province' => 'pesaro_urbino',
            'meeting_point' => 'Parcheggio Gola del Furlo',
            'latitude' => 43.6500,
            'longitude' => 12.7500,
            'parking_info' => 'Parcheggio gratuito disponibile',
            'what_to_bring' => 'Costume da bagno, asciugamano, cambio vestiti',
            'user_types' => ['singolo', 'coppia', 'amici'],
            'age_groups' => ['14-18'],
            'group_types' => ['gruppi_15+', 'team_building'],
            'disabilities' => [],
            'pets_allowed' => false,
            'has_offer' => true,
            'free_cancellation' => true,
            'is_new' => false,
            'few_spots_left' => true,
            'tour_type' => 'group',
            'sustainability_score' => 90,
            'small_association' => true,
            'price_adult' => 65.00,
            'price_child' => null,
            'price_senior' => null,
            'price_group' => 60.00,
            'season' => 'high',
            'available_from' => now(),
            'available_to' => now()->addMonths(4),
            'min_participants' => 6,
            'max_participants' => 12,
            'cutoff_hours' => 48,
            'cancellation_policy' => 'flexible',
            'weather_cancellation' => true,
            'indoor_alternative' => false,
            'images' => [],
            'video_url' => null,
            'status' => 'active',
            'rating' => 4.9,
            'reviews_count' => 28,
        ]);

        // Esperienza 3: Degustazione Vini
        Experience::create([
            'vendor_id' => $vendor1->id,
            'category_id' => $enogastronomia->id,
            'title' => 'Degustazione Vini nelle Colline del Verdicchio',
            'short_description' => 'Tour enogastronomico tra le cantine del Verdicchio',
            'full_description' => 'Un pomeriggio dedicato alla scoperta del Verdicchio, il vino simbolo delle Marche. Visiteremo due cantine storiche, degusteremo vini pregiati abbinati a prodotti tipici locali. Esperienza perfetta per gli amanti del buon vino.',
            'languages' => ['it', 'en', 'fr', 'de'],
            'has_lis' => false,
            'has_braille' => false,
            'start_time_period' => 'afternoon',
            'duration' => '3-5h',
            'location_type' => 'campagna',
            'province' => 'ancona',
            'meeting_point' => 'Cantina Castelli di Jesi',
            'latitude' => 43.5200,
            'longitude' => 13.2400,
            'parking_info' => 'Parcheggio disponibile presso le cantine',
            'what_to_bring' => 'Designated driver consigliato',
            'user_types' => ['singolo', 'coppia', 'amici', 'senior'],
            'age_groups' => [],
            'group_types' => ['gruppi_15+', 'addio_nubilato'],
            'disabilities' => [],
            'pets_allowed' => false,
            'has_offer' => false,
            'free_cancellation' => true,
            'is_new' => false,
            'few_spots_left' => false,
            'tour_type' => 'group',
            'sustainability_score' => 75,
            'small_association' => false,
            'price_adult' => 55.00,
            'price_child' => null,
            'price_senior' => 50.00,
            'price_group' => 50.00,
            'season' => 'high',
            'available_from' => now(),
            'available_to' => now()->addMonths(8),
            'min_participants' => 2,
            'max_participants' => 15,
            'cutoff_hours' => 24,
            'cancellation_policy' => 'flexible',
            'weather_cancellation' => false,
            'indoor_alternative' => true,
            'images' => [],
            'video_url' => null,
            'status' => 'active',
            'rating' => 4.8,
            'reviews_count' => 19,
        ]);

        // Esperienza 4: Trekking Monti Sibillini
        Experience::create([
            'vendor_id' => $vendor2->id,
            'category_id' => $natura->id,
            'title' => 'Trekking nei Monti Sibillini',
            'short_description' => 'Escursione naturalistica nel Parco Nazionale dei Monti Sibillini',
            'full_description' => 'Una giornata immersi nella natura del Parco Nazionale dei Monti Sibillini. Percorreremo sentieri panoramici, ammireremo la flora e la fauna locale e raggiungeremo punti panoramici mozzafiato. Guida naturalistica esperta.',
            'languages' => ['it', 'en'],
            'has_lis' => false,
            'has_braille' => false,
            'start_time_period' => 'morning',
            'duration' => '5h_to_1day',
            'location_type' => 'montagna',
            'province' => 'macerata',
            'meeting_point' => 'Centro Visite Parco Sibillini',
            'latitude' => 42.9500,
            'longitude' => 13.2000,
            'parking_info' => 'Parcheggio disponibile al punto di partenza',
            'what_to_bring' => 'Scarpe da trekking, zaino, pranzo al sacco, acqua, crema solare',
            'user_types' => ['singolo', 'coppia', 'amici', 'famiglia'],
            'age_groups' => ['10-14', '14-18'],
            'group_types' => ['gruppi_15+'],
            'disabilities' => [],
            'pets_allowed' => true,
            'has_offer' => false,
            'free_cancellation' => true,
            'is_new' => true,
            'few_spots_left' => false,
            'tour_type' => 'group',
            'sustainability_score' => 95,
            'small_association' => true,
            'price_adult' => 35.00,
            'price_child' => 20.00,
            'price_senior' => 30.00,
            'price_group' => 30.00,
            'season' => 'high',
            'available_from' => now(),
            'available_to' => now()->addMonths(5),
            'min_participants' => 3,
            'max_participants' => 18,
            'cutoff_hours' => 24,
            'cancellation_policy' => 'flexible',
            'weather_cancellation' => true,
            'indoor_alternative' => false,
            'images' => [],
            'video_url' => null,
            'status' => 'active',
            'rating' => 4.6,
            'reviews_count' => 8,
        ]);

        $this->command->info('Esperienze create con successo!');
    }
}
